require("dotenv").config();
const mongoose = require("mongoose");
const cors = require("cors");
const swaggerUi = require("swagger-ui-express");
const swaggerSpec = require("./swagger");
const bodyParser = require("body-parser");
const express = require("express");
const app = express();
const flightRoutes = require("./routes/flight.routes");
const bookingRoutes = require("./routes/booking.routes");
const userRoutes = require("./routes/user.routes");
app.use(cors("*"));
app.use(express.json());
app.use(bodyParser.urlencoded({ limit: "10mb", extended: false }));
app.use("/api", userRoutes);
app.use("/api", flightRoutes);
app.use("/api", bookingRoutes);
app.use("/api", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
mongoose.connect(process.env.DATABASE_URL);
const db = mongoose.connection;
db.on("error", (err) => console.error(err));
db.once("open", () => console.log("connected to db"));
app.listen(3500);
